#Set the Duoshuo shortName
duoshuo_shortName: dogod 

#Personal Information
name: Dogod
signature: Keep coding,go up everday!
location: GuangZhou,China

about: 中山大学软件工程15级硕士在读,前端、Node.js爱好者。


#socail Information
github: https://github.com/Jianglinyuan
weibo: http://weibo.com/949459420
email: leonjiang1121@gmail.com

