#Set the Duoshuo shortName
duoshuo_shortName: dogod 

#Personal Information
name: Dogod
signature: Keep coding,go up everday!
location: GuangZhou,China

about: 『你的个人简介』


#socail Information
github: https://github.com/Jianglinyuan
weibo: http://weibo.com/949459420
email: leonjiang1121@gmail.com

